name: 'Vulnerability alerts'

on:
  schedule:
    - cron: '0 9 * * 1' # every Monday at 9 AM
  workflow_dispatch:

permissions:
  contents: read
  vulnerability-alerts: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: kunalnagarco/action-cve@v1.17.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          count: 30 # limited in the action's code
          severity: critical,high
